<?xml version = "1.0" ?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.265" />
    <xacro:property name="base_width" value="0.16" />
    <xacro:property name="base_height" value="0.08" />

    <xacro:property name="wheel_radius" value="0.04" />
    <xacro:property name="wheel_width" value="0.02" />

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <material name="argint"/>
            </visual>
            <xacro:cylinder_inertia m="0.1" r="${wheel_radius}" h="${wheel_width}" o_xyz="0 0 0" o_rpy="${pi/2} 0 0"/>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                    <!-- <cylinder radius="${wheel_radius}" length="${wheel_width}"/> -->
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </collision>
        </link>
    </xacro:macro>

    <link name="base_footprint" />

    <joint name="base_base_footprint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius * 2}" rpy="0 0 0"/>
    </joint>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
            <material name="black"/>
        </visual>
        <xacro:box_inertia m="1.9" x="${base_length}" y="${base_width}" z="${base_height}" o_xyz="0 0 ${base_height / 2}" o_rpy="0 0 0"/>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
        </collision>
    </link>

    <joint name="base_front_left" type="continuous">
        <parent link="base_link"/>
        <child link="front_left_wheel_link"/>
        <origin xyz="0.09 ${(base_width / 2) + (wheel_width /2)} -${wheel_radius}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <xacro:wheel_link prefix="front_left"/>

    <joint name="base_front_right" type="continuous">
        <parent link="base_link"/>
        <child link="front_right_wheel_link"/>
        <origin xyz="0.09 -${(base_width / 2) + (wheel_width /2)} -${wheel_radius}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <xacro:wheel_link prefix="front_right"/>

    <joint name="base_rear_left" type="continuous">
        <parent link="base_link"/>
        <child link="rear_left_wheel_link"/>
        <origin xyz="-0.09 ${(base_width / 2) + (wheel_width /2)} -${wheel_radius}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <xacro:wheel_link prefix="rear_left"/>

    <joint name="base_rear_right" type="continuous">
        <parent link="base_link"/>
        <child link="rear_right_wheel_link"/>
        <origin xyz="-0.09 -${(base_width / 2) + (wheel_width /2)} -${wheel_radius}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <xacro:wheel_link prefix="rear_right"/>

    <joint name="base_tof" type="fixed">
        <parent link="base_link"/>
        <child link="tof_link"/>
        <origin xyz="${base_length / 2} 0 ${base_height}" rpy="0 0 0"/>
    </joint>

    <link name="tof_link">
        <visual>
            <geometry>
                <box size="0.01 0.01 0.02"/>
            </geometry>
            <origin xyz="-0.005 0 0.01" rpy="0 0 0"/>
            <material name="galben"/>
        </visual>
    </link>

    <joint name="base_imu" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="-${base_length / 2} 0 ${(base_height / 2)}" rpy="0 0 0"/>
    </joint>

    <link name="imu_link">
        <visual>
            <geometry>
                <box size="0.01 0.01 0.02"/>
            </geometry>
            <origin xyz="0.005 0 0.01" rpy="0 0 0"/>
            <material name="galben"/>
        </visual>
    </link>

</robot>